# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '6.x'
  artifactName: 'my-app-$(Build.BuildId)' # Dynamic artifact name based on build ID
  mvcArtifactName: 'mvc-app-$(Build.BuildId)'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: $(dotnetVersion)
      installationPath: $(Agent.ToolsDirectory)/dotnet
    
  - script: dotnet build src/Monolithic/MvcApp/MvcApp.csproj --configuration $(buildConfiguration)
    displayName: 'Build Web App'

  - script: dotnet publish src/Monolithic/MvcApp/MvcApp.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publish WebApp'
  

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: $(mvcArtifactName)
    displayName: 'publish artifacts'