# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.x'
  artifactName: 'drop-$(Build.BuildId)' # Dynamic artifact name based on build ID

steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: $(dotnetVersion)
      installationPath: $(Agent.ToolsDirectory)/dotnet
    
  - script: dotnet build src/Monolithic/MvcApp/MvcApp.csproj --configuration $(buildConfiguration)
    displayName: 'Build Web App'
  
  - task: DotNetCoreCLI@2
    displayName: 'Publish Web App'
    inputs:
      command: publish
      publishWebProjects: true
      arguments: 'src/Monolithic/MvcApp/MvcApp.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: $(artifactName)
    displayName: 'publish artifacts'